added first version of challenge
BTU-Cyber-Security-and-CTF-Club/Challenges pull request #25
Opened 2023-10-09 19:34 UTC by ripcurlz

players have to connect to TCP port 8080 with either e.g. netcat, telnet or sth. similar. They have to respond with the correct answer to the origin of the provided md5 hash.

if they get the answer right, they are greeted by a nyancat cli, every 10th second the flag is displayed in there.

2023-10-13 18:12 UTC, B-Schwarz requested changes
Please change the hash and don't comment the solution as this repo is public

Otherwise it worked

2023-10-13 18:12 UTC, B-Schwarz commented on Misc/nyaned_enough/challenge.pl
> +# 5badcaf789d3d1d09794d8f021f40f0e is the md5 of the word "starwars"
This repo is public so better change it ^^

2023-10-14 08:38 UTC, ripcurlz commented on Misc/nyaned_enough/challenge.pl
> +# 5badcaf789d3d1d09794d8f021f40f0e is the md5 of the word "starwars"
changed it

2023-10-14 11:35 UTC, B-Schwarz approved these changes
I now see my problem with the earlier change request 🤣 

As the password is in clear at the if condition the changing of the hash is irrelevant, so I could've approved the first pull request ^^

2023-10-14 11:35 UTC, merged